# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Date-Pregnancy
version:      0.02
version_from: lib/Date/Pregnancy.pm
installdirs:  site
requires:
    Carp:                          0
    Clone:                         0
    DateTime:                      0
    Exporter:                      0
    File::Find:                    0
    File::Spec:                    0
    POSIX:                         0
    Test::More:                    0
    Test::Pod:                     0.95
    Test::Pod::Coverage:           0.08

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.25
